### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by plavist** [Perfare/Riru-Il2CppDumper#29]
I install module for Cytus 2 and launch app,but i dont see dump.cs in /data/data/com.rayark.cytus2/files.
Where can i see logs?

**Comment by sterling0x1** [comment]
adb logcat -s Perfare

**Comment by niknah** [comment]
This is the version to use with the latest Riru, the version here doesn't have an "init" function...

https://github.com/JasonKhew96/Riru-Il2CppDumper

I also had to run
`ln -s /data/adb/riru /data/misc/riru`

For some reason riru keeps on deleting /data/misc/riru/api_version, so that needs to be re-created some times...
`echo -n 10 >/data/misc/riru/api_version`


But now the app crashes...

> I Perfare : detect game: ...
> I Perfare : hack thread: 6781
> I Perfare : api level: 26
> I Perfare : __loader_dlopen at: 0xf046a47d


> F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf086b482 in tid 6762 (...)
